<h1>Analysis results</h1>

<div class="tab-view" id="tabs">
	<nav>
		<ul>
			<li>
				<a class="active" href="#tab-project">Project</a>
			</li>
			<li>
				<a href="#tab-complexity">Complexity</a>
			</li>
			<li>
				<a href="#tab-unitsize">Size</a>
			</li>
			<li>
				<a href="#tab-duplication">Duplication</a>
			</li>
		</ul>
	</nav>

	<section class="tab-sheet active" id="tab-project">
		<div id="chart-ranks" class="chart"></div>
	</section>

	<section class="tab-sheet" id="tab-complexity">
		<div id="chart-complexity" class="chart"></div>
		<div id="methods-complexity" class="data-list"></div>
	</section>

	<section class="tab-sheet" id="tab-unitsize">
		<div id="chart-unitsize" class="chart"></div>
		<div id="methods-unitsize" class="data-list"></div>
	</section>

	<section class="tab-sheet" id="tab-duplication">
		<div id="chart-duplication" class="chart"></div>
		<div id="methods-duplication" class="data-list"></div>
	</section>
</div>
