<!DOCTYPE html>
<html lang="<?php echo $this->culture->getLocale() ?>" dir="<?php echo $this->culture->getReadingDirection() ?>">
	<head>
		<meta charset="<?php echo $this->culture->getCharset() ?>" />
		<link rel="stylesheet" type="text/css" media="all" href="/assets/css/default.css" />
		<title><?php echo $this->title ?></title>
	</head>

	<body>
		<?php echo $this->noEscape( 'content' ) ?>

		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
		<script type="text/javascript" src="/assets/js/rest.js"></script>
		<script type="text/javascript" src="/assets/js/tabview.js"></script>
		<script type="text/javascript" src="/assets/js/main.js"></script>
	</body>
</html>
