<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />

		<link rel="stylesheet" type="text/css" media="all" href="/assets/css/default.css" />

		<title>PHP Analyzer</title>
	</head>
	<body>
		<header>
			<h1>Analysis results</h1>
		</header>

		<div>
		</div>

		<footer></footer>

		<script type="text/javascript" src="/data/load.php"></script>
		<script type="text/javascript" src="/assets/js/main.js"></script>
	</body>
</html>